#pragma once
typedef struct _DEVICE_CONTEXT
{
    WDFDEVICE WdfDevice;
    PDEVICE_OBJECT WdmDevObj;
    WDFQUEUE IoQueue;
    HANDLE BfeStateHandle;  //BFE state subscription handle
    WFP_KERNEL_CONTEXT WfpCtx;
} DEVICE_CONTEXT, * PDEVICE_CONTEXT;
WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(DEVICE_CONTEXT, DeviceGetContext)

typedef struct _QUEUE_CONTEXT {
    ULONG PlaceHolder;
} QUEUE_CONTEXT, * PQUEUE_CONTEXT;
WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(QUEUE_CONTEXT, QueueGetContext)
